import { Ionicons } from '@expo/vector-icons'
import { LinearGradient } from 'expo-linear-gradient'
import { useRouter } from 'expo-router'
import React from 'react'
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { signOut } from 'firebase/auth'
import { auth } from '../../firebase/firebase'
import { LogoutConfirmModal } from '../../components/LogoutConfirmModal'

const orders = [{ id: 'ORD-0056', name: 'Maria Santos', service: 'Wash & Fold • Regular', status: 'Washing', color: '#D7F0FF' }, { id: 'ORD-0048', name: 'Carlo Lim', service: 'Wash & Fold • Rush', status: 'Washing', color: '#D7F0FF' }, { id: 'ORD-0046', name: 'Nita Cruz', service: 'Dry Cleaning', status: 'Completed', color: '#D5F3E1' }]
function Nav({ active, router, onLogout }: { active: string; router: ReturnType<typeof useRouter>; onLogout: () => void }) { return <View style={styles.nav}>{[['home', 'home', 'Home'], ['orders', 'receipt', 'Orders'], ['payment', 'card', 'Records']].map(([key, icon, label]) => <Pressable key={key} onPress={() => router.replace(`/staff/${key}`)} style={styles.navItem}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={20} color={active === key ? '#0877C8' : '#71879A'} /><Text style={[styles.navLabel, active === key && styles.active]}>{label}</Text></Pressable>)}<Pressable onPress={onLogout} style={styles.navItem}><Ionicons name="log-out-outline" size={20} color="#71879A" /><Text style={styles.navLabel}>Log Out</Text></Pressable></View> }
export default function StaffOrders() { const router = useRouter(); const [showLogout, setShowLogout] = React.useState(false); const [loggingOut, setLoggingOut] = React.useState(false); const handleLogout = async () => { setLoggingOut(true); try { await signOut(auth); router.replace('/staff/login') } finally { setLoggingOut(false); setShowLogout(false) } }; return <View style={styles.screen}><LinearGradient colors={['#BEE9FF', '#F7FCFF', '#FFFFFF']} style={StyleSheet.absoluteFill} /><SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Image source={require('../../assets/img/logo.png')} style={styles.logo} resizeMode="contain" /><View><Text style={styles.brand}>Branch Orders</Text><Text style={styles.role}>Nabunturan Branch</Text></View></View><View style={styles.search}><Ionicons name="search-outline" size={16} color="#7590A1" /><Text style={styles.searchText}>Search order or customer</Text></View>{orders.map((order) => <View key={order.id} style={styles.card}><View style={styles.icon}><Ionicons name="receipt" size={17} color="#0877C8" /></View><View style={styles.copy}><Text style={styles.id}>{order.id}</Text><Text style={styles.name}>{order.name}</Text><Text style={styles.meta}>{order.service}</Text></View><View style={[styles.status, { backgroundColor: order.color }]}><Text style={styles.statusText}>{order.status}</Text></View><Ionicons name="chevron-forward" size={16} color="#7893A4" /></View>)}</ScrollView><Nav active="orders" router={router} onLogout={() => setShowLogout(true)} /></SafeAreaView><LogoutConfirmModal visible={showLogout} loading={loggingOut} onCancel={() => setShowLogout(false)} onConfirm={() => void handleLogout()} /></View> }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFFFFF' }, safe: { flex: 1 }, content: { width: '100%', maxWidth: 420, alignSelf: 'center', padding: 11, paddingBottom: 18 }, header: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 }, logo: { width: 44, height: 38 }, brand: { color: '#075191', fontSize: 15, fontWeight: '800' }, role: { color: '#6B879B', fontSize: 7, marginTop: 2 }, search: { height: 31, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 9, borderRadius: 5, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D3E3EC' }, searchText: { color: '#94A4AE', fontSize: 8 }, card: { minHeight: 66, flexDirection: 'row', alignItems: 'center', padding: 8, marginTop: 8, borderRadius: 7, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D3E3EC' }, icon: { width: 30, height: 30, alignItems: 'center', justifyContent: 'center', borderRadius: 5, backgroundColor: '#E1F3FF' }, copy: { flex: 1, marginLeft: 8 }, id: { color: '#075191', fontSize: 9, fontWeight: '800' }, name: { color: '#395E73', fontSize: 8, marginTop: 2 }, meta: { color: '#79909E', fontSize: 7, marginTop: 3 }, status: { paddingHorizontal: 6, paddingVertical: 3, marginRight: 6, borderRadius: 6 }, statusText: { color: '#0877C8', fontSize: 6, fontWeight: '800' }, nav: { minHeight: 57, flexDirection: 'row', backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#B6DDEF' }, navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 }, navLabel: { color: '#71879A', fontSize: 7 }, active: { color: '#0877C8', fontWeight: '800' } })