import { Ionicons } from '@expo/vector-icons'
import { LinearGradient } from 'expo-linear-gradient'
import { useRouter } from 'expo-router'
import React from 'react'
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { signOut } from 'firebase/auth'
import { auth } from '../../firebase/firebase'
import { LogoutConfirmModal } from '../../components/LogoutConfirmModal'

const payments = [{ id: 'ORD-0048', name: 'Any Reyes', amount: 'P350.00', type: 'Wash & Fold • Regular', date: 'Sep 27, 2026 - 3:40 PM' }, { id: 'ORD-0041', name: 'Carlo Lim', amount: 'P280.00', type: 'Wash & Fold • Rush', date: 'Sep 26, 2026 - 5:10 PM' }, { id: 'ORD-0038', name: 'Nita Cruz', amount: 'P420.00', type: 'Dry Cleaning', date: 'Sep 25, 2026 - 1:20 PM' }]
function Nav({ active, router, onLogout }: { active: string; router: ReturnType<typeof useRouter>; onLogout: () => void }) { return <View style={styles.nav}>{[['home', 'home', 'Home'], ['orders', 'receipt', 'Orders'], ['payment', 'card', 'Records']].map(([key, icon, label]) => <Pressable key={key} onPress={() => router.replace(`/staff/${key}`)} style={styles.navItem}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={20} color={active === key ? '#0877C8' : '#71879A'} /><Text style={[styles.navLabel, active === key && styles.active]}>{label}</Text></Pressable>)}<Pressable onPress={onLogout} style={styles.navItem}><Ionicons name="log-out-outline" size={20} color="#71879A" /><Text style={styles.navLabel}>Log Out</Text></Pressable></View> }
export default function StaffPayment() { const router = useRouter(); const [showLogout, setShowLogout] = React.useState(false); const [loggingOut, setLoggingOut] = React.useState(false); const handleLogout = async () => { setLoggingOut(true); try { await signOut(auth); router.replace('/staff/login') } finally { setLoggingOut(false); setShowLogout(false) } }; return <View style={styles.screen}><LinearGradient colors={['#BEE9FF', '#F7FCFF', '#FFFFFF']} style={StyleSheet.absoluteFill} /><SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Image source={require('../../assets/img/logo.png')} style={styles.logo} resizeMode="contain" /><View><Text style={styles.brand}>Payment Records</Text><Text style={styles.role}>Nabunturan Branch</Text></View></View><View style={styles.filter}><Text style={styles.filterText}>Today’s verified payments</Text><Ionicons name="chevron-down" size={14} color="#668395" /></View>{payments.map((payment) => <View key={payment.id} style={styles.card}><View style={styles.top}><View style={styles.icon}><Ionicons name="card" size={17} color="#0877C8" /></View><Text style={styles.id}>{payment.id}</Text><Text style={styles.amount}>{payment.amount}</Text></View><Text style={styles.name}>{payment.name}</Text><Text style={styles.meta}>{payment.type}</Text><Text style={styles.date}>{payment.date}</Text><View style={styles.verified}><Ionicons name="checkmark-circle" size={11} color="#15914D" /><Text style={styles.verifiedText}>Verified</Text></View></View>)}</ScrollView><Nav active="payment" router={router} onLogout={() => setShowLogout(true)} /></SafeAreaView><LogoutConfirmModal visible={showLogout} loading={loggingOut} onCancel={() => setShowLogout(false)} onConfirm={() => void handleLogout()} /></View> }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#FFFFFF' }, safe: { flex: 1 }, content: { width: '100%', maxWidth: 420, alignSelf: 'center', padding: 11, paddingBottom: 18 }, header: { flexDirection: 'row', alignItems: 'center', marginBottom: 18 }, logo: { width: 44, height: 38 }, brand: { color: '#075191', fontSize: 15, fontWeight: '800' }, role: { color: '#6B879B', fontSize: 7, marginTop: 2 }, filter: { height: 31, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 9, borderRadius: 5, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D3E3EC' }, filterText: { color: '#668395', fontSize: 8 }, card: { minHeight: 106, padding: 9, marginTop: 9, borderRadius: 7, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D3E3EC' }, top: { flexDirection: 'row', alignItems: 'center' }, icon: { width: 29, height: 29, alignItems: 'center', justifyContent: 'center', borderRadius: 5, backgroundColor: '#E1F3FF' }, id: { marginLeft: 7, color: '#075191', fontSize: 9, fontWeight: '800' }, amount: { marginLeft: 'auto', color: '#075191', fontSize: 10, fontWeight: '800' }, name: { color: '#45697C', fontSize: 8, marginTop: 8 }, meta: { color: '#79909E', fontSize: 7, marginTop: 4 }, date: { color: '#79909E', fontSize: 7, marginTop: 4 }, verified: { position: 'absolute', right: 9, bottom: 8, flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 5, paddingVertical: 2, borderRadius: 5, backgroundColor: '#D5F3E1' }, verifiedText: { color: '#15914D', fontSize: 6, fontWeight: '800' }, nav: { minHeight: 57, flexDirection: 'row', backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#B6DDEF' }, navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 }, navLabel: { color: '#71879A', fontSize: 7 }, active: { color: '#0877C8', fontWeight: '800' } })