import { Ionicons } from '@expo/vector-icons'
import { LinearGradient } from 'expo-linear-gradient'
import { useRouter } from 'expo-router'
import React, { useState } from 'react'
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { signOut } from 'firebase/auth'
import { auth } from '../../firebase/firebase'
import { LogoutConfirmModal } from '../../components/LogoutConfirmModal'

const payments = [
	{ id: 'ORD-0048', amount: 'P350.00', customer: 'Any Reyes', branch: 'Nabunturan Branch', date: 'Sep 27, 2026 - 3:40 PM' },
	{ id: 'ORD-0041', amount: 'P280.00', customer: 'Carlo Lin', branch: 'Maco Branch', date: 'Sep 26, 2026 - 5:10 PM' },
	{ id: 'ORD-0038', amount: 'P420.00', customer: 'Nita Cruz', branch: 'Nabunturan Branch', date: 'Sep 25, 2026 - 1:20 PM' },
]

export default function AdminPayment() {
	const router = useRouter()
	const [branch, setBranch] = useState('All Branches')
	const [showLogout, setShowLogout] = useState(false)
	const [loggingOut, setLoggingOut] = useState(false)
	return <View style={styles.screen}><LinearGradient colors={['#C5E9FC', '#F4FBFF', '#DFF4FF']} style={StyleSheet.absoluteFill} /><Image source={require('../../assets/img/bubble2.png')} style={styles.bubble} resizeMode="contain" /><SafeAreaView style={styles.safeArea}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
		<View style={styles.topBar}><Pressable onPress={() => router.replace('/admin/home')} accessibilityLabel="Go to admin home"><Ionicons name="arrow-back" size={21} color="#0877C8" /></Pressable><View style={styles.heading}><Text style={styles.title}>Payment History</Text><Text style={styles.subtitle}>Review all verified transactions</Text></View><View style={styles.topSpacer} /></View>
		<View style={styles.filters}><Pressable onPress={() => setBranch(branch === 'All Branches' ? 'Nabunturan Branch' : 'All Branches')} style={styles.filter}><Text style={styles.filterText}>{branch}</Text><Ionicons name="chevron-down" size={13} color="#587487" /></Pressable><Pressable style={styles.filter}><Text style={styles.filterText}>All Staff</Text><Ionicons name="chevron-down" size={13} color="#587487" /></Pressable></View>
		{payments.map((payment) => <View key={payment.id} style={styles.paymentCard}><View style={styles.paymentTop}><View style={styles.receipt}><Ionicons name="receipt" size={18} color="#0877C8" /></View><Text style={styles.orderId}>{payment.id}</Text><Text style={styles.amount}>{payment.amount}</Text></View><View style={styles.divider} /><Text style={styles.meta}><Text style={styles.metaLabel}>Customer  </Text>{payment.customer}</Text><Text style={styles.meta}><Text style={styles.metaLabel}>Branch       </Text>{payment.branch}</Text><Text style={styles.meta}><Text style={styles.metaLabel}>Date & Time  </Text>{payment.date}</Text><View style={styles.verified}><Ionicons name="checkmark-circle" size={12} color="#15914D" /><Text style={styles.verifiedText}>Verified</Text></View></View>)}
	</ScrollView><AdminNav active="payments" onNavigate={(screen) => router.replace(screen === 'home' ? '/admin/home' : screen === 'staff' ? '/admin/staff' : '/admin/payment')} onLogout={() => setShowLogout(true)} /></SafeAreaView><LogoutConfirmModal visible={showLogout} loading={loggingOut} onCancel={() => setShowLogout(false)} onConfirm={async () => { setLoggingOut(true); try { await signOut(auth); router.replace('/admin') } finally { setLoggingOut(false); setShowLogout(false) } }} /></View>
}

function AdminNav({ active, onNavigate, onLogout }: { active: string; onNavigate: (screen: string) => void; onLogout: () => void }) { return <View style={styles.bottomNav}>{[['home', 'home', 'Home'], ['staff', 'people', 'Staff'], ['payments', 'card', 'Payments']].map(([key, icon, label]) => <Pressable key={key} onPress={() => onNavigate(key)} style={styles.navItem}><Ionicons name={icon as keyof typeof Ionicons.glyphMap} size={21} color={active === key ? '#0877C8' : '#71879A'} /><Text style={[styles.navLabel, active === key && styles.activeNavLabel]}>{label}</Text></Pressable>)}<Pressable onPress={onLogout} style={styles.navItem}><Ionicons name="log-out-outline" size={21} color="#71879A" /><Text style={styles.navLabel}>Log Out</Text></Pressable></View> }

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#E3F4FF' }, safeArea: { flex: 1 }, content: { width: '100%', maxWidth: 420, alignSelf: 'center', padding: 10, paddingBottom: 18 }, bubble: { position: 'absolute', width: 130, height: 130, top: 50, right: -53, opacity: 0.35 }, topBar: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: 10 }, heading: { flex: 1 }, title: { color: '#075191', fontSize: 15, fontWeight: '800' }, subtitle: { color: '#668395', fontSize: 8, marginTop: 2 }, topSpacer: { width: 21 }, filters: { flexDirection: 'row', gap: 8, marginTop: 13 }, filter: { flex: 1, height: 31, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 8, borderRadius: 5, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D2E0E8' }, filterText: { color: '#597587', fontSize: 8 }, paymentCard: { minHeight: 130, padding: 10, marginTop: 10, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.96)', borderWidth: 1, borderColor: '#D2E0E8' }, paymentTop: { flexDirection: 'row', alignItems: 'center' }, receipt: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center', borderRadius: 5, backgroundColor: '#E1F3FF' }, orderId: { marginLeft: 8, color: '#075191', fontSize: 9, fontWeight: '800' }, amount: { marginLeft: 'auto', color: '#075191', fontSize: 10, fontWeight: '800' }, divider: { height: 1, backgroundColor: '#E5EDF2', marginVertical: 7 }, meta: { color: '#47697D', fontSize: 7, lineHeight: 13 }, metaLabel: { color: '#8A9CA8' }, verified: { position: 'absolute', right: 10, bottom: 9, flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 5, paddingVertical: 2, borderRadius: 5, backgroundColor: '#D8F6E4' }, verifiedText: { color: '#15914D', fontSize: 6, fontWeight: '800' }, bottomNav: { minHeight: 59, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around', borderTopWidth: 1, borderTopColor: '#A9D8F2', backgroundColor: 'rgba(255,255,255,0.96)' }, navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 }, navLabel: { color: '#71879A', fontSize: 8 }, activeNavLabel: { color: '#0877C8', fontWeight: '800' } })
